import MoreHorizIcon from "@mui/icons-material/MoreHoriz";
import FavoriteOutlinedIcon from "@mui/icons-material/FavoriteOutlined";
import FavoriteBorderOutlinedIcon from "@mui/icons-material/FavoriteBorderOutlined";
import DeleteIcon from "@mui/icons-material/DeleteOutlined";
import TextsmsOutlinedIcon from "@mui/icons-material/TextsmsOutlined";
import ShareOutlinedIcon from "@mui/icons-material/ShareOutlined";
import ArrowBackIosIcon from "@mui/icons-material/ArrowBackIos";
import KeyboardArrowDIcon from "@mui/icons-material/KeyboardArrowDown";
import MaximizeIcon from "@mui/icons-material/Maximize";
import MinimizeIcon from "@mui/icons-material/Minimize";
import FacebookTwoToneIcon from "@mui/icons-material/FacebookTwoTone";
import LinkedInIcon from "@mui/icons-material/LinkedIn";
import InstagramIcon from "@mui/icons-material/Instagram";
import PinterestIcon from "@mui/icons-material/Pinterest";
import TwitterIcon from "@mui/icons-material/Twitter";
import PlaceIcon from "@mui/icons-material/Place";
import LanguageIcon from "@mui/icons-material/Language";
import EmailOutlinedIcon from "@mui/icons-material/EmailOutlined";
import MoreVerticonIcon from "@mui/icons-material/MoreVert";
import SearchOutlinedIcon from "@mui/icons-material/SearchOutlined";
import PersonOutlinedIcon from "@mui/icons-material/PersonOutlined";
import DarkModeOutlinedIcon from "@mui/icons-material/DarkModeOutlined";
import NotificationOutlinedIcon from "@mui/icons-material/NotificationsOutlined";
import HomeOutlinedIcon from "@mui/icons-material/HomeOutlined";
import PowerSettingsNewIcon from "@mui/icons-material/PowerSettingsNew";
import WbSunnyOutLined from "@mui/icons-material/WbSunnyOutlined";
import GridViewOutlinedIcon from "@mui/icons-material/GridViewOutlined";

export const MoreHoriz = MoreHorizIcon;
export const FavoriteOutlined = FavoriteOutlinedIcon;
export const FavoriteBorderOutlined = FavoriteBorderOutlinedIcon;
export const Delete = DeleteIcon;
export const Textsms = TextsmsOutlinedIcon;
export const Share = ShareOutlinedIcon;
export const ArrowBackIos = ArrowBackIosIcon;
export const KeyboardArrowD = KeyboardArrowDIcon;
export const Minimize = MinimizeIcon;
export const Maximize = MaximizeIcon;
export const Facebook = FacebookTwoToneIcon;
export const LinkedIn = LinkedInIcon;
export const Instagram = InstagramIcon;
export const Pinterest = PinterestIcon;
export const Twitter = TwitterIcon;
export const Place = PlaceIcon;
export const Language = LanguageIcon;
export const Email = EmailOutlinedIcon;
export const MoreVerticon = MoreVerticonIcon;
export const SearchIcon = SearchOutlinedIcon;
export const ProfileIcon = PersonOutlinedIcon;
export const DarkModeIcon = DarkModeOutlinedIcon;
export const NotificationIcon = NotificationOutlinedIcon;
export const HomeIcon = HomeOutlinedIcon;
export const PowerIcon = PowerSettingsNewIcon;
export const WbSunny = WbSunnyOutLined;
export const GridView = GridViewOutlinedIcon;
